### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ThatXliner** [ThatXliner/lark_shell#3]
- [X] Get it working
- [X] Better UI
   - [X] Show Lark version
   - [X] Scrollable
- [x] Clean up the code
   - [x] Catch the expected errors
   - [x] Present the errors well
- [x] Add more options
   - [x] Option to change parser
   - [ ] Option to solve ambiguity (Earley only)
   - [ ] Lexer options
   - [ ] Command line options
- [ ] Exporting
  - [ ] Export to file
  - [ ] Copy to clipboard
 - [ ] Get it bundled with lark
